### ISSUE TITLE
List JSON gets corrupted

### ISSUE THREAD

**Issue by hyperknot** [ITCase/pyramid_sacrud#105]
I'm using a JSON column type, as per your recommendation:

```
Column(JSON, info={'colanderalchemy': {'widget': deform.widget.TextAreaWidget(cols=80, rows=4)}}, default={})
```

This works well for dict JSONs, however it doesn't work for JSONs which represent a list. For example: `[1,2,3]`

If you enter `[1,2,3]`, the following is saved to the database: `1`

**Comment by uralbash** [comment]
@hyperknot  Thanks for report bug. I fixed it in new sacrud version == 0.3.4.
Just update:
```bash
pip install sacrud -U
```
