### ISSUE TITLE
Startpage in 2.0 is a bit too strong

### ISSUE THREAD

**Issue by hyperknot** [ITCase/pyramid_sacrud#109]
I believe that pyramid sacrud 1.x had a nice and elegant design.

Having just upgraded to 2.0, I've seen that 70% of the start space is taken over by sacrud "about" info. This made me question my belief in the direction of the project and I decided to start implementing my own admin using WTForms-Alchemy.

While the default design is entirely the decision of the creator, I'd recommend going back to something more subtle, like 1.x  was. 

<img width="1155" alt="screen shot 2015-12-01 at 14 40 43" src="https://cloud.githubusercontent.com/assets/494223/11502195/ab3028f2-9839-11e5-89e9-02e299e3204a.png">

**Comment by uralbash** [comment]
Old man who supported and wrote 1.x Design is no longer support this. Previous design have much undocumented legacy css code and undocumented spaghetti gulp file for build this. Therefore I rewrote interface with webpack and materialize-css, it's pretty easy to edit and contribute. But I have a weak skills of frontend and design, and, therefore it require assistance with CSS master. At the moment I can do header and bottom more subtle.

**Comment by hyperknot** [comment]
I was only talking about the visuals, not the code. I mean, I cannot make a simple admin interface and give it to a customer, they'd ask "Why is Help pyramid_sacrud Grow written in the admin?"

**Comment by uralbash** [comment]
ok, I remove this footer in 0.2.1 version. As a temporary solution you can redefine template in your project (templates/sacrud/redefineme.jinja2) like this:

```jinja

{% extends "sacrud/base.jinja2" %}

{% block footer %}
  <footer class="page-footer blue-grey darken-1">
    &copy; 2013-<script>document.write(new Date().getFullYear())</script>, 
    YourCompanyName.
  </footer>
{% endblock %}
```

or make your own footer see http://materializecss.com/footer.html or remove it completely:

```jinja

{% extends "sacrud/base.jinja2" %}

{% block footer %}{% endblock %}
```

![sacrud_-_home_-_2015-12-01_20 25 07](https://cloud.githubusercontent.com/assets/619015/11504957/ad688bf2-9869-11e5-88b2-bc63e0d43786.png)

**Comment by hyperknot** [comment]
Thanks a lot, this it's much better!

**Comment by uralbash** [comment]
This changes in 0.2.1 version now.
