### ISSUE TITLE
Composite Rows

### ISSUE THREAD

**Issue by pejoo** [ITCase/pyramid_sacrud#79]
I see in commit 91c80b1cbabd782edaa56dcd33337b6961400c96 you remove the common/custom.py file that contains the WidgetRowLambda definition used to define composite rows, is there a new method of doing this? The documentation at https://github.com/ITCase/pyramid_sacrud/blob/master/docs/pages/configuration.rst still shows to use WidgetRowLambda but that no longer exists in the github version of the code.

**Comment by uralbash** [comment]
Principle enough to create a class with attributes and ``name`` and ``info.sacrud_list_content``.

```python
class Widget(object):
    name = "Foo"
    info = {
        "sacrud_list_content": lambda x: "foooooooooooo",
    }
```

and add it to ``sacrud_list_col``:

```python

sacrud_list_col = [name, email, Widget()]
```

![_105](https://cloud.githubusercontent.com/assets/619015/6981862/4aa04ad8-da22-11e4-9a95-a8982cb911b4.png)

I can describe it in the documentation and close the task, if it solves the problem.

**Comment by pejoo** [comment]
Ya, if that is the new way to do it then just updating the docs would be great. Just needed to know the new way so I can update my code to work with it :smile:

**Comment by uralbash** [comment]
Ok, I have written documentation and released a new version. (http://pyramid-sacrud.readthedocs.org/en/latest/pages/configuration.html#composite-fields-and-column-as-custom-function). 
In this version, many changes, now model support ColanderAlchemy config (see http://colanderalchemy.readthedocs.org/en/latest/customization.html) and much more. If you have something that does not work, just write tasks or use freenode IRC #sacrud
