### ISSUE TITLE
Version 0.0.5 broken when updating sacrud_deform and sacrud

### ISSUE THREAD

**Issue by pejoo** [ITCase/pyramid_sacrud#80]
The new changes in the latest version of sacrud break the current PyPi version of pyramid_sacrud. Any ETA on when 0.0.6 will be done and released so pip can find it when installing all requirements?

**Comment by uralbash** [comment]
Version 0.0.6 fix everything, I will try to publish it in the near future. I need to solve only one task #79

**Comment by uralbash** [comment]
Now on PyPi
