### ISSUE TITLE
ItemsView object is not scriptable

### ISSUE THREAD

**Issue by pejoo** [ITCase/pyramid_sacrud#84]
I see a pull request was already made and merged to fix this for Python 3, I am wondering when a new version will be added to PyPi with the fix. I prefer to use pip install <package> since that is what setuptools uses when installing requirements but it is currently adding another step to the setup process to grab it from Github instead for the fix.

**Comment by uralbash** [comment]
I updated version on PyPi to 0.0.7, try it out.
