### ISSUE TITLE
checkbox (boolean field) edit issue

### ISSUE THREAD

**Issue by pagenoare** [ITCase/pyramid_sacrud#94]
Im having 2 fields in my models which are Boolean Type; when I set them to `true` it works fine, the problem exists when I'm trying to revoke it, ie set it to `false`. It says it has been updated, but it's not.

I'm using sqlite3.

I'll dig into the sources and trace what is happening (and maybe propose a PR), but don't have time for that now, that's why Im creating this issue.

Thanks,
Kacper.

**Comment by uralbash** [comment]
I tried to reproduce this problem, and could not get.

Check  model Good in https://github.com/ITCase/pyramid_sacrud/tree/master/example, it works for me.
And check the dependencies:
colander==1.0
deform==2.0a2

If the problem is not solved, could you make an example.

**Comment by pagenoare** [comment]
Hey @uralbash 

Thanks for the reply. I'll try to figure out what's causing the issue and create a example project for that, but right now I'm kinda busy with my day job, so no clue when i'll have some time for it :P (propably next weekend).

**Comment by pagenoare** [comment]
@uralbash I think it's related to using `default=False` in `sa.Column()`; removed that flag and it works OK.

**Comment by uralbash** [comment]
@pagenoare 
Yes, you're right, it is a bug. I fixed it in the new version of [sacrud](https://github.com/ITCase/sacrud). Just do ``pip install sacrud -U``.
Thank you for reported error.

**Comment by pagenoare** [comment]
I can confirm that it's working fine now. Thanks for the fix and whole package of course :-)

Have a great evening!
