### ISSUE TITLE
`Unauthorized: sa_home failed permission check` how to handle this error?

### ISSUE THREAD

**Issue by cundi** [ITCase/pyramid_sacrud#97]
I follow the official docs, and set it step by step.
Using browser point to http://localhost:6543/sacrud/, here raise 403 Forbidden error.
I'm trying to delete sa_home function's parameter permission in  pyramid_sacrud/views/__init__.py  to solve it, though It could be access but it hasn't  login page in there.

```
403 Forbidden

Access was denied to this resource.

Unauthorized: sa_home failed permission check
```

**Comment by uralbash** [comment]
I have created an example with authorization (https://github.com/ITCase/pyramid_sacrud/tree/master/example), in your case, you seem to have edit ``pyramid_sacrud/views/init.py`` file that is not location in a python env or not reload server.

**Comment by cundi** [comment]
@uralbash thanks I'll try it.

**Comment by uralbash** [comment]
@cundi  I hope it is solved.
