### ISSUE TITLE
How can i implementation richtext editor in a admin interface way.

### ISSUE THREAD

**Issue by cundi** [ITCase/pyramid_sacrud#98]
I mean that accomplish this purpose just like Django's AdminModel.  
Each of Model's field has its richtext editor instance.   
It would be the screen shot in following.   
![2015-09-26 6 18 04](https://cloud.githubusercontent.com/assets/10941075/10117035/68e78356-647b-11e5-80f3-7afc9095ea1f.png)

**Comment by cundi** [comment]
Actually I'm new in Pyramid, so I asking such questions.

**Comment by uralbash** [comment]
You can add any class in any field. https://github.com/stefanofontanelli/ColanderAlchemy uses to generate the scheme forms. You can use all the features of this module. In your problem, you need to make a textarea field and add the CSS class (for example ``tinymce``).

Ok, I'll take an example from the documentation (http://pyramid-sacrud.readthedocs.org/en/latest/pages/configuration.html#add-css-class-for-column):

```python

tinymce_widget = deform.widget.TextAreaWidget(css_class='tinymce content')


class TestCustomizing(Base):
    __tablename__ = "test_customizing"

    id = Column(Integer, primary_key=True)
    description = Column(Text, info={'colanderalchemy': {'widget': tinymce_widget}})
```

Now your field is TextArea and has CSS classes ``tinymce`` and ``content``. The next step is to add the WYSIWYG editor (http://www.tinymce.com/wiki.php/Installation) in your template:
```html
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="<your installation path>/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea.tinymce"
        });
    </script>
</head>
<body>
...
</body>
</html>
```
That's all. See results:

![column_css](https://cloud.githubusercontent.com/assets/619015/10117722/a8258dc6-6479-11e5-8672-2aa9666620f3.png)

My tinymce config:

```html
{% block js %}
  {{ super() }}
  <script src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>
  <script>
    tinymce.init({
      selector:'textarea.tinymce',
      forced_root_block : false,
      height : 400,
      width : 1024,
      relative_urls: false,
      convert_urls: true,
      remove_script_host : true,
      browser_spellcheck : true,
      content_css: ["{{ request.static_url('mjemcorp.app:static/css/tinymce.css') }}", ],
      plugins: "image link code contextmenu fullpage fullscreen "+
              "hr insertdatetime lists media paste preview "+
              "print table textcolor "+
              "visualchars wordcount",
      toolbar1: "fullpage preview print forecolor backcolor inserttable",
      toolbar2: "styleselect formatselect fontselect fontsizeselect cut copy paste  removeformat subscript superscript",
      toolbar3: "undo redo | bold italic underline strikethrough | bullist numlist outdent indent blockquote | alignleft aligncenter alignright alignjustify |",
    });
  </script>
{% endblock %}
```

**Comment by cundi** [comment]
I appreciate that your answer for me。🌹

**Comment by uralbash** [comment]
@cundi I hope it is resolved. Ask me if there's any need.
