### ISSUE TITLE
Not working with JSON columns

### ISSUE THREAD

**Issue by hyperknot** [ITCase/pyramid_sacrud#99]
I have a JSON column, imported from `sqlalchemy.dialects.postgresql` and pyramid_sacrud seems not being able to recognise it as a JSON type.

If I go to an object's page in the admin which contains a JSON field, it returns:

> NotImplementedError: Not able to derive a colander type from
> sqlalchemy type: JSON()  Please explicitly provide a colander 'typ'
> for the "geojson" Column.

My problem is that I found no information on the internet about how can I set the a 'typ' column for my JSON column. How can I fix it?

**Comment by uralbash** [comment]
pyramid_sacrud uses  for configuration ``colanderalchemy``.  Therefore, for each field of model, you can override his type for form (see docs http://colanderalchemy.readthedocs.org/en/latest/customization.html#worked-example).

```python

class MyModel(Base):
    geojson = Column(
        JSON,
        info={'colanderalchemy': {
            'typ': colander.String(),
            'widget': deform.widget.TextAreaWidget(),
        }})
```

Such a solution would be to write json as a string. It's not right, I'll try to fix it in the next release.

**Comment by hyperknot** [comment]
Thanks, that solves part of the problem but it replaces valid JSON into an escaped string. So

`{"a": 1, "c": 3, "b": 2}` becomes 

`"{u\'a\': 1, u\'c\': 3, u\'b\': 2}"`

Is there any way to disable this escaping and use json.loads / dumps as serializers?

**Comment by hyperknot** [comment]
I wrote a custom colander type, which works well:

```
class JSONType(colander.SchemaType):
    def serialize(self, node, appstruct):
        if appstruct is colander.null:
            return colander.null

        return json.dumps(appstruct, indent=2, ensure_ascii=False)


    def deserialize(self, node, cstruct):
        if not cstruct:
            return colander.null

        try:
            return json.loads(cstruct)
        except Exception:
            raise colander.Invalid(node, '"{}" is not a valid JSON'.format(cstruct))
```

**Comment by uralbash** [comment]
@hyperknot thanks a lot! I rewrote the logic now if ``typ`` is not defined it set as ``JSONType`` (see https://github.com/ITCase/sacrud_deform/commit/228d5c8e75e10e2b50177eadad09290892153a88).

Update version of ``sacrud>=0.3.3`` and ``sacrud_deform>=0.0.9``:

```python
pip install -U sacrud sacrud_deform
```
And then you can do so (without set ``typ``):
``` python
class MyModel(Base):
    geojson = Column(
        JSON,
        info={'colanderalchemy': {
            'widget': deform.widget.TextAreaWidget(),
        }})
```

**Comment by hyperknot** [comment]
Thanks, works well!
